# >>> IF YOU CHANGE CONFIG RESTART SERVER: "⌃C + bundle exec jekyll serve" <<<

# 1. Build
# 2. Collections
# 3. Front Matter
# 4. Plugins
# 5. Variables

# BUILD ==================================================

## Server (localhost)
port: 4002

## Warnings
strict_front_matter: true
liquid:
  error_mode: strict

## Final _site
exclude:
  - README.md
  - Gemfile.lock # jekyll
  - Gemfile
  - /vendor
  - /docker-compose.yml # docker
  - /docker-start
  - config.codekit3 # codekit3
  - cache
  - log
  - logs
  - node_modules
  - /storage/framework/sessions

# COLLECTIONS ==================================================

## Docs
collections:
  docs:
    permalink: /:collection/:path/
    output: true # render .MD files to HTML on build

# FRONT MATTER ==================================================

## Settings
defaults:
  -
    scope:
      path: "" # empty string means all files in the project
      type: "pages" # select pages only
    values:
      layout: "page"
      lang: "en"
  -
    scope:
      path: "_docs"
      type: "docs" # created in collections
    values:
      layout: "article"
      lang: "en"
      custom_title: null # add custom title variable in docs article if needed

## Conversion
permalink: pretty
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true # disable Rouge highliter
  parse_block_html: true # in .MD files render MD inside HTML blocks

# PLUGINS ==================================================

## Github --safe
plugins:
  - jemoji

# VARIABLES ==================================================

## Site variables
title: "Smartsupp API"
google_analytics_id: "UA-40155471-3"
smartlook_id: "d49100746188e1c96b748403c518e72e897d8748"
github_username: smartsupp
git_repo: smartsupp.github.io

## Custom variables
# (add if needed)

## Product
pr_author: "Smartsupp"
pr_name: "Smartsupp"
pr_url: "https://www.smartsupp.com/"
pr_url_name: "Smartsupp.com"
pr_email: "info@smartsupp.com"
pr_description: "Smartsupp API. Developer DOCS."

## Url
url_docs_root: "/docs/"

## Pages
pa_github: "Smartsupp GitHub"
pa_docs: "Docs"

## Categories
ca_customization: "Chat Box Customization"
ca_javascript_api: "JavaScript API"
ca_examples: "Examples"

### Categories (description)
ca_d_customization: "Customize chat box features and behaviour."
ca_d_javascript_api: "Adjust chat box to fit your needs."
ca_d_examples: "Browse API code examples."

### Categories (URL)
ca_url_customization: "/docs/customization/"
ca_url_javascript_api: "/docs/javascript-api/"
ca_url_examples: "/docs/examples/"