version: '2'
services:
  site:
    image: jekyll/jekyll:pages
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4002:4002
      - 35729:35729
    command: ./docker-start
